source :rubygems

gem "sinatra"
gem "sinatra-reloader"

gem 'sprockets' #, :git => 'git://github.com/sstephenson/sprockets.git'
gem 'coffee-script'
gem 'sass'
gem 'haml'
gem 'rack-test'
gem 'sinatra'

group :development do
  gem "compass"
  gem "guard"
  gem "guard-coffeescript"
  gem "guard-compass"
  gem "growl"
end